[project]
name = "backend-svc"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.95.2",
    "uvicorn[standard]>=0.22.0",
    "pydantic>=1.10.9",
    "requests>=2.13.0,<3.0.0"
]
